### ISSUE TITLE
Manage s2download/sen2cor errors and temporary files

### ISSUE THREAD

**Issue by ranghetti** [ranghetti/fidolasen#36]
When sen2cor or download crash, temporary files created in the filesystem are not removed.
Manage that in order not to leave temporary files (the problem is urgent in case user quotas exist).

**Comment by ranghetti** [comment]
Done with commits 68a21aa037b64f77d09cd8b2f5c615b6118ce88b (create functions) and 8614394287f2bd042a998840fbecc5d6422f9ff6 (apply functions).
Note that a method to detect errors in call to sen2cor is still missing; a function which check the required content of output L2A folders (jp2 files) should be built.

**Comment by lbusett** [comment]
:+1:
