### ISSUE TITLE
Add message about what tile is being processed before starting sen2cor

### ISSUE THREAD

**Issue by lbusett** [ranghetti/fidolasen#41]
e.g., : Starting sen2cor correction - tile 1 of XXX -> Name of the image

**Comment by ranghetti** [comment]
Take into account problems related to log messages inside a foreach %dopar% cycle ([example](https://stackoverflow.com/questions/10903787/how-can-i-print-when-using-dopar)). 
A possible workaround could be to split the %dopar%  cycle in sub-groups of products, runned in a standard for cycle, with messages for each sub-group (e.g "Starting sen2cor on tiles A, B, C, D ,E, F - tiles 1-6 of 50"). This can slow the global execution (each sub-group would end only when the correction of last product ends).
Any other suggestions?

**Comment by lbusett** [comment]
Acc... true.... ;-)
